name: Update README Activity

on:
  workflow_dispatch: {}            # 可手動執行
  schedule:
    - cron: "0 */6 * * *"          # 每 6 小時跑一次（可調）

permissions:
  contents: write                  # 只開需要的最小權限
  pull-requests: read

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # 產生最近活動（最近合併 PR + 最近 commits）
      - name: Generate recent activity
        id: gen
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.REPO_TOKEN }}   # 使用你剛設定的 Secret
          script: |
            const owner = context.repo.owner;
            const repo  = context.repo.repo;
            const per = 5;

            // 取最近合併的 PR
            const prs = await github.rest.pulls.list({
              owner, repo, state: 'closed', per_page: 20, sort: 'updated', direction: 'desc'
            });
            const merged = prs.data.filter(p => p.merged_at).slice(0, per);

            // 取最近 commits
            const commits = await github.rest.repos.listCommits({ owner, repo, per_page: per });

            function d(s){ return new Date(s).toISOString().slice(0,10); }
            const prLines = merged.map(p => `- Merged PR [#${p.number} ${p.title}](${p.html_url}) on ${d(p.merged_at)}`);
            const commitLines = commits.data.map(c => `- ${c.sha.slice(0,7)} ${c.commit.message.split('\n')[0]} (${d(c.commit.author.date)})`);

            const md = [
              '### Recent Merged PRs',
              ...prLines,
              '',
              '### Recent Commits',
              ...commitLines
            ].join('\n');

            core.setOutput('content', md);

      # 將內容寫回 README 標記之間
      - name: Update README between markers
        shell: bash
        run: |
          set -euo pipefail
          file="README.md"
          start="<!-- RECENT_ACTIVITY:start -->"
          end="<!-- RECENT_ACTIVITY:end -->"
          if ! grep -q "$start" "$file" || ! grep -q "$end" "$file"; then
            echo "::error ::README markers not found"; exit 1
          fi
          content="${{ steps.gen.outputs.content }}"
          perl -0777 -pe 's/'"$start"'.*?'"$end"'/('"$start"'."\n".qq|'${content//'|'/'\|'}'|."\n".'"$end"')/s' "$file" > README.new
          mv README.new "$file"

      - name: Commit & push changes
        env:
          GH_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          if git diff --quiet; then
            echo "No README changes"; exit 0
          fi
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore(readme): update recent activity [skip ci]"
          git push "https://${GH_TOKEN}@github.com/${{ github.repository }}.git" HEAD:${GITHUB_REF_NAME:-main}
