name: YAML Sanity

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        shell: bash
        run: |
          echo "YAML indentation OK on ${{ github.ref_name }}"
